Task5
Mahiminho/csad2425ki404popovmy16 pull request #11
Opened 2024-11-23 11:47 UTC by Mahiminho

2024-11-23 16:22 UTC, PavloFedakNULP requested changes
Please add screen with % of coverage by tests

2024-11-23 16:32 UTC, Mahiminho commented
![изображение](https://github.com/user-attachments/assets/5221eb18-407a-44e2-b01a-d774792f666b)

Unfortunately, the Qt framework that I use to write the client part of app and its testing library (QTest) dont have the functionality to calculate coverage directly, so I`ll use a script to run the tests from the command line and show it against the background of running tests in the environment.

2024-11-23 16:34 UTC, Mahiminho commented
Or do I need to commit this screen to this branch?

2024-11-24 19:10 UTC, PavloFedakNULP approved these changes

2024-11-24 19:12 UTC, merged